name: Deploy

on:
  release:
    types:
      - released
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # https://github.com/actions/cache/blob/f4278025ab0f432ce369118909e46deec636f50c/examples.md#node---npm
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)" >> $GITHUB_OUTPUT

      - name: Load npm cache
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci --cache ${{ steps.npm-cache-dir.outputs.dir }}

      - name: Compile
        run: npm run build

      # Cloudflare has a custom action to run wrangler commands: cloudflare/wrangler-action@2.0.0
      # However, it interfers with the actions/cache command.
      # It appears to create a `.wrangler` directory which cannot be scanned.
      # The GitHub Actions debug log had this error:
      #    Error: EACCES: permission denied, scandir '/home/runner/work/loop-supreme/loop-supreme/.wrangler'
      # Since wrangler is already a dependency, we can skip the custom action and just run the command directly
      - name: Publish
        run: CLOUDFLARE_API_TOKEN=${{ secrets.CF_API_TOKEN }} CLOUDFLARE_ACCOUNT_ID=${{ secrets.CF_ACCOUNT_ID }} npm run wrangler pages publish build -- --project-name=loopsupreme --branch production
